//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S3A_LEVEQUE_GUIMBEAU
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_Classe_CLS> T_Classe_CLS { get; set; }
        public virtual DbSet<T_Eleve_ELV> T_Eleve_ELV { get; set; }
        public virtual DbSet<T_Epreuve_EPR> T_Epreuve_EPR { get; set; }
        public virtual DbSet<T_Recompense_RCP> T_Recompense_RCP { get; set; }
        public virtual DbSet<V_ELV_qqClasses_qqNoms> V_ELV_qqClasses_qqNoms { get; set; }
    }
}
