//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S3A_LEVEQUE_GUIMBEAU
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Classe_CLS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Classe_CLS()
        {
            this.T_Eleve_ELV = new HashSet<T_Eleve_ELV>();
        }
    
        public decimal CLS_Num { get; set; }
        public string CLS_Intit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Eleve_ELV> T_Eleve_ELV { get; set; }
    }
}
