//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S3A_LEVEQUE_GUIMBEAU
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Eleve_ELV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Eleve_ELV()
        {
            this.T_Eleve_ELV1 = new HashSet<T_Eleve_ELV>();
            this.T_Epreuve_EPR = new HashSet<T_Epreuve_EPR>();
            this.T_Recompense_RCP = new HashSet<T_Recompense_RCP>();
        }
    
        public decimal ELV_Id { get; set; }
        public Nullable<decimal> ELV_REF_ELV { get; set; }
        public decimal ELV_REF_CLS { get; set; }
        public string ELV_Nom { get; set; }
        public decimal ELV_AnneeNais { get; set; }
        public string ELV_VilleNais { get; set; }
    
        public virtual T_Classe_CLS T_Classe_CLS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Eleve_ELV> T_Eleve_ELV1 { get; set; }
        public virtual T_Eleve_ELV T_Eleve_ELV2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Epreuve_EPR> T_Epreuve_EPR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Recompense_RCP> T_Recompense_RCP { get; set; }
    }
}
