//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S3A_LEVEQUE_GUIMBEAU
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Epreuve_EPR
    {
        public decimal EPR_REF_ELV { get; set; }
        public string EPR_Abrv { get; set; }
        public Nullable<decimal> EPR_Note { get; set; }
    
        public virtual T_Eleve_ELV T_Eleve_ELV { get; set; }
    }
}
