//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S3A_LEVEQUE_GUIMBEAU
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ELV_qqClasses_qqNoms
    {
        public decimal ELV_Id { get; set; }
        public Nullable<decimal> ELV_REF_ELV { get; set; }
        public decimal ELV_REF_CLS { get; set; }
        public string ELV_Nom { get; set; }
        public decimal ELV_AnneeNais { get; set; }
        public string ELV_VilleNais { get; set; }
    }
}
